# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Utils/02_uncache.ipynb.

# %% auto 0
__all__ = ['uncache']

# %% ../../nbs/Utils/02_uncache.ipynb 3
import sys

# %% ../../nbs/Utils/02_uncache.ipynb 5
def uncache(
    exclude: str,  # excluded packages
) -> None:
    "Remove package modules from cache except excluded ones. On next import they will be reloaded."
    # Init packages
    pkgs = []
    # Append packages to exclude
    for mod in exclude:
        pkg = mod.split(".", 1)[0]
        pkgs.append(pkg)

    # Remove packages from cache
    to_uncache = []
    # loop over modules
    for mod in sys.modules:
        if mod in exclude:
            continue
        if mod in pkgs:
            to_uncache.append(mod)
            continue
        for pkg in pkgs:
            if mod.startswith(pkg + "."):
                to_uncache.append(mod)
                break
    for mod in to_uncache:
        del sys.modules[mod]
