# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/betting_agent',
                'doc_host': 'https://MeherKharbachi.github.io',
                'git_url': 'https://github.com/MeherKharbachi/betting_agent',
                'lib_path': 'betting_agent'},
  'syms': {'betting_agent.core': {'betting_agent.core.foo': ('core.html#foo', 'betting_agent/core.py')}}}
